### ISSUE TITLE
Unable to claim a transfer for the BSC-xDai OB

### ISSUE THREAD

**Issue by akolotov** [omni/omnibridge-ui#258]
Currently the history page for my account shows the following unclaimed transfer:
![image](https://user-images.githubusercontent.com/20793260/124490303-98137680-ddba-11eb-9c9b-fc03ab679710.png)

But when I press the Claim button the following message appears:
![image](https://user-images.githubusercontent.com/20793260/124490411-b9746280-ddba-11eb-9b8f-2264e8a3088b.png)

ALM also reports that the transfer was already executed:
https://alm-bsc-xdai.herokuapp.com/100/0x3d32ad2a7153582505adf9ef0205b0401d679a0b4b6e8e7e91b189d26ce9b5eb

**Comment by dan13ram** [comment]
Hey I see that the AMB also reports "Manual Execution Waiting" on https://alm-bsc-xdai.herokuapp.com/100/0x3d32ad2a7153582505adf9ef0205b0401d679a0b4b6e8e7e91b189d26ce9b5eb
And its stuck at "Searching Transaction"
![Screenshot from 2021-07-08 22:19:02](https://user-images.githubusercontent.com/10012209/124961001-8fc96e80-e03a-11eb-9d60-8f02205f8368.png)

If you know its executed, can you share the execution transaction with me so I can debug further ?

**Comment by akolotov** [comment]
This is the transaction finalized the transfer: https://bscscan.com/tx/0x0a7951834d9c046be59f04925f29e931a58b684008fa7c08e5d1f6259422cc49

**Comment by dan13ram** [comment]
So the issue is with the subgraph and I'm unable to deploy and test new ones because of an issue with the graph.
https://status.thegraph.com/incidents/xnpt4405fjbp

This issue is pretty old already and the graph team haven't responded yet with an ETA. 

The issue has to do with the RPC endpoint that the graph is using with their graph-nodes for BSC network.
